# frozen_string_literal: true

require 'app/descent'

module Descent
  module Tilesheet
    PATH = 'sprites/tilesheet.png'
    TILE_SIZE = 32
    COLUMNS = 17
    ROWS = 17

    # Generated from sprites/main_32x32.json (pack version 1.2.0).
    # Names run left-to-right, top-to-bottom; their indices are the tile IDs.
    # A string avoids DragonRuby's operand limit for a 289-entry hash literal.
    TILES = <<~NAMES.split.map(&:to_sym).each_with_index.to_h.freeze
      worn_flagstone
      pale_flagstone
      black_flagstone
      square_medallion
      dark_mosaic
      cracked_mosaic
      red_compass
      blood_mosaic
      round_seal
      cross_medallion
      dark_cross
      stone_cross
      crypt_soil
      gray_crypt_soil
      dark_crypt_soil
      skull_soil
      sandy_crypt_soil
      mossy_soil
      bone_soil
      red_carpet
      gold_border_carpet
      narrow_red_runner
      double_gold_carpet
      gold_trim_carpet
      sigil_carpet
      worn_red_carpet
      blue_carpet
      torn_carpet
      violet_carpet
      dark_carpet
      broken_carpet
      stained_carpet
      inset_floor
      stone_corner
      stone_bend
      stone_elbow
      stone_inner_corner
      stone_recess
      stone_wall_junction
      column_wall
      stone_t_wall
      cross_wall
      white_column_wall
      double_column_wall
      triple_column_wall
      red_carpet_corner
      blood_spill_carpet
      cracked_carpet
      slate_roof
      slate_roof_gable
      gray_roof_gable
      ribbed_roof_gable
      dark_roof_gable
      stone_wall_break
      pointed_window
      brick_wall
      rose_window
      small_rose_window
      tall_rose_window
      red_pane_window
      blood_rose_window
      arched_iron_window
      crimson_window
      pointed_stone_window
      arched_wood_door
      barred_arch_door
      narrow_arch_door
      heavy_iron_door
      open_stone_arch
      shadow_arch
      small_open_arch
      gargoyle_wall_panel
      round_stone_column
      fluted_column
      ornate_column
      recessed_wall_panel
      cross_wall_panel
      red_banner
      torn_red_banner
      hanging_red_banner
      wide_stone_stairs
      ascending_left_stairs
      ascending_stone_stairs
      ascending_right_stairs
      red_ladder
      wooden_ladder
      iron_fence
      spiked_fence
      tall_iron_fence
      narrow_iron_fence
      rounded_gravestone
      cross_gravestone
      arched_gravestone
      pointed_gravestone
      broad_cross_gravestone
      small_gravestone
      carved_pew
      plain_pew
      scroll_pew
      short_pew
      choir_seat
      lectern
      red_cloth_altar
      candle_altar
      cabinet_organ
      pipe_organ
      large_brass_bell
      hanging_brass_bell
      five_branch_candelabra
      three_branch_candelabra
      brass_candelabra
      narrow_candelabra
      hooded_statue
      winged_gargoyle
      crouching_gargoyle
      seated_gargoyle
      closed_stone_coffin
      raised_stone_coffin
      wooden_coffin
      ornate_stone_coffin
      gold_coffin
      carved_sarcophagus
      arched_reliquary
      wooden_reliquary
      gray_reliquary
      iron_cage
      red_hanging_cage
      tall_iron_cage
      red_candle
      tall_red_candle
      melted_pillar_candle
      triple_candles
      skull_pair
      skull_stack
      small_bone_pile
      large_bone_pile
      skull_heap
      red_petal_scatter
      bloody_debris
      iron_shackles
      hanging_chain
      round_chain
      bloodied_chain
      red_sacrificial_pedestal
      open_prayer_book
      open_scripture
      red_grimoire
      violet_grimoire
      open_bone_grimoire
      gold_key
      silver_key
      iron_key
      ornate_gold_key
      horned_pendant
      blue_pendant
      gold_cross
      ruby_cross
      round_key
      gold_coin
      ritual_coin
      simple_sword
      cross_hilt_sword
      silver_dagger
      wooden_hammer
      double_axe
      ornate_axe
      incense_burner
      ritual_sword
      bronze_hand_mirror
      round_red_potion
      blue_flask
      round_blue_potion
      red_flask
      black_flask
      square_red_potion
      oval_mirror
      anatomical_heart
      skull
      purple_soul_flame
      blue_soul_flame
      violet_soul_flame
      purple_flame
      purple_orb
      carved_emblem
      gold_crown
      iron_crown
      thorn_ring
      gold_ring
      horned_mask
      gold_sun_emblem
      red_seal
      purple_void
      stone_rubble
      skull_rubble
      broken_masonry
      broken_column
      rubble_mound
      bare_tree
      twisted_tree
      tall_bare_tree
      blood_tree
      small_bare_tree
      silver_bare_tree
      chain_gallows
      dark_chain_gallows
      blood_well
      red_portal
      dark_well
      cracked_red_seal
      glowing_red_seal
      red_ritual_grid
      cracked_dark_seal
      dark_blue_seal
      blue_rune_ring
      blue_rune_circle
      blue_ripple_circle
      icy_ripple_circle
      blue_water_ring
      green_poison_splash
      green_poison_pool
      red_shield
      blue_shield
      blue_gold_shield
      cross_shield
      red_heart
      black_heart
      blue_potion_icon
      red_drop
      gold_star
      purple_eye
      ivory_skull
      green_skull
      hand_glove
      leather_boot
      scroll
      gold_key_icon
      gold_coin_icon
      coin_pouch
      gold_crown_icon
      small_fire
      medium_fire
      tall_fire
      wide_fire
      fire_streak
      fire_orb_small
      fire_orb_medium
      fire_orb_large
      fire_burst
      ice_spark_small
      ice_spark_medium
      ice_star
      ice_burst
      ice_trail
      purple_spark
      purple_orb_small
      purple_orb_medium
      purple_orb_large
      purple_star
      holy_spark
      holy_pillar_small
      holy_pillar
      holy_pillar_wide
      holy_pillar_large
      poison_flame_wide
      poison_pillar
      purple_spikes_small
      purple_spikes
      purple_spikes_wide
      purple_spikes_large
      purple_spikes_tall
      gold_sigil_small
      gold_sigil_medium
      gold_sigil_large
      gold_sigil_wide
      ice_spikes_small
      ice_spikes
      ice_spikes_wide
      ice_spikes_large
      ice_spikes_tall
      purple_ring_small
      purple_ring
      purple_ring_wide
      purple_ring_large
      purple_ring_bright
      red_spikes_small
      red_spikes
      red_spikes_wide
      red_spikes_large
      red_spikes_tall
    NAMES

    def self.source_rect(name)
      id = TILES.fetch(name)
      {
        x: (id % COLUMNS) * TILE_SIZE,
        y: (ROWS - 1 - id.div(COLUMNS)) * TILE_SIZE,
        w: TILE_SIZE,
        h: TILE_SIZE
      }
    end
  end
end
